### ISSUE TITLE
[Theme]: enight

### ISSUE THREAD

**Issue by end-4** [hyprland-community/theme-repo#2]
### git repository which includes your theme

https://github.com/end-4/enight

**Comment by flickowoa** [comment]
this repo requires themes to follow a certain format so they can be parsed, check out the `theme.toml` format at https://github.com/hyprland-community/hyprtheme readme

or alternatively take a look at the example `aurora` theme

**Comment by end-4** [comment]
i made a `theme.toml`
tell me if there are any other problems
you should also include this requirement in the repo's readme

**Comment by flickowoa** [comment]
can you hv `hyprland.conf` used by theme.toml be as minimal as possible, without any binds and other stuff, you can make a seperate `theme.conf` file with the necessary configs and use that in theme.toml instead, then source that in hyprland.conf to use it  in your dotfiles as usual 

or better
you can make another repo with just your theme.conf and bars without any general config like binds.

the idea is so when a user installs the theme they wont hv to install a totally different set of binds, instead they can go along using their own

**Comment by flickowoa** [comment]
im sorry for the lack of a proper wiki/guide rn but its being worked on and should make these more clear once finished

**Comment by end-4** [comment]
no problem

https://github.com/end-4/enight

**Comment by flickowoa** [comment]
yep, lgtm, but just a small thing you will hv to either edit the original issue with this link or create a new issue with this link for the github worklflow for approving to work

**Comment by end-4** [comment]
okay edited

**Comment by flickowoa** [comment]
also, rn u are using `exec-once ` they will require u to relogin after applying theme, using `exec` is gonna be a better option here to apply changes as soon as theme is applied, this will require some extra exec lines that kill other bars like waybar or other eww bars

**Comment by flickowoa** [comment]
> this will require some extra exec lines that kill other bars like waybar or other eww bars

you can now use `hyprtheme kill` to kill all bars/wallpaper daemons
