### ISSUE TITLE
[HYPRLAND] 

### ISSUE THREAD

**Issue by Cybersnake223** [hyprland-community/theme-repo#26]
### Name

Vicious Viper 

### Repo

https://github.com/Cybersnake223/Hypr

### Branch

main

### Config

https://github.com/Cybersnake223/Hypr/blob/main/hypr/hyprland.conf

**Comment by flickowoa** [comment]
Hey, thanks for contributing your dotfiles to the theme-repo but we don't really work with full on dotfiles (just yet)  theme-repo is a repo for so called "themes" which are configs that only have decorative elements meant to be imported onto another base hyprland config 
( More info about how themes work will be added once theme-repo and hyprtheme are ready to be used )

we are planning to also house full dotfiles but it's not very finished yet

**Comment by Cybersnake223** [comment]
Okayy ill be waiting then until you are ready with working on full on dotfiles until then imma keep improving it.  
Thanks .
